Tableaux Numpy

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4,5]

In [ ]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [ ]:
nested_list = [[1,2], [3,5]]

In [ ]:
nested_list_test

[[1, 2], [3, 5]]

In [ ]:
np.array(nested_list)

array([[1, 2],
       [3, 5]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.randn(2)

array([1.40870883, 1.48173439])

In [ ]:
np.random.randn(5,5)

array([[ 1.25894915, -1.46307861,  2.03828844, -0.46943344, -0.05559888],
       [ 1.00815056,  0.39337111, -1.6154556 , -0.55722469,  0.43955614],
       [ 0.94472389,  0.29819666, -0.6066569 ,  0.38935404, -0.0581481 ],
       [ 0.30407723,  0.67491766, -2.58369029, -1.20484165,  0.06057688],
       [ 0.04243636,  0.30330694, -0.46761056, -0.46127757,  0.83431877]])

In [ ]:
np.random.randint(1,100,10)

array([88,  2, 43, 23,  5,  3, 31, 64, 89, 27])

In [ ]:
np.random.seed(40)
np.random.randint(1,100,10)

array([71, 92,  8, 38, 57, 51, 66, 13, 72, 20])

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
arr.shape

(25,)

In [ ]:
ranarr

array([31, 10, 19, 27,  9, 32, 49,  9,  8, 30])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.argmax()

6

In [ ]:
ranarr.min()

8

In [ ]:
ranarr.dtype

dtype('int64')

In [ ]:
myarr = np.random.rand(4)

In [ ]:
myarr.dtype

dtype('float64')

Selection et Indexation

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
slice_of_arr = arr[0:6]

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_of_arr[:] = 99

In [ ]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:] = 100

In [ ]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
arr_2d[1][0]

20

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
bool_arr = arr > 4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

Operation Numpy

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr -1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [ ]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [ ]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [ ]:
arr.sum()

55

In [ ]:
arr.min()

1

In [ ]:
arr.mean()

5.5

In [ ]:
arr.std()

2.8722813232690143

In [ ]:
arr_2d = np.arange(0,25).reshape(5,5)

In [ ]:
arr_2d.shape

(5, 5)

In [ ]:
arr_2d.sum()

300

In [ ]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [ ]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])